### PR TITLE
Add relationship between radiology exam and result

### PR DESCRIPTION
**Pull request by Lucas-Masaba**
### Here, I did the following ⚙️ 
- Modify models to add relationships.
- Add a column to params for radiology results.
- Modify tests to match relationships.

### CODE REVIEW

**Comment by Lucas-Masaba** [comment]
[Relationship between Radiology_exam and Radiology_result](https://trello.com/c/PwHfC9R8/55-relationship-between-radiologyexam-and-radiologyresult)

**Comment by Lucas-Masaba** [comment]
[Relationship between Radiology_exam and Radiology_result](https://trello.com/c/PwHfC9R8/55-relationship-between-radiologyexam-and-radiologyresult)

**Comment by Lucas-Masaba** [comment]
[Relationship between Radiology_exam and Radiology_result](https://trello.com/c/PwHfC9R8/55-relationship-between-radiologyexam-and-radiologyresult)

**Review by kemigabocatherine — APPROVED** [review]
### APPROVED :100: 

-  Amazing work on the project!! It's time to merge your project :tada: :tada: 

thumbs-up

**Pull request merged**
